### ISSUE TITLE
Libp2p node does not create stream under certain conditions

### ISSUE THREAD

**Issue by ChronosX88** [MoonSHRD/p2chat#28]
## Steps to reproduce
1. Run libp2p node on Android
2. Run libp2p node on PC
### Expected behavior
Stream will be created normally.
### Actual behavior
Nothing happened.
#### Comment:
Stream will be created only if the first run libp2p node is on the PC.

**Comment by JackBekket** [comment]
It seems like android can't open stream

**Comment by JackBekket** [comment]
but not sure that I can reproduce it, but I will try

**Comment by JackBekket** [comment]
This bug may have appear only at build/streams branch, I'm closing this issue, cause low-level streams are deprecated in new PubSub branch
