### ISSUE TITLE
Decrease weight of p2hcat repo by squash commits and rebasing master branch

### ISSUE THREAD

**Issue by JackBekket** [MoonSHRD/p2chat#58]
p2hcat repo is to big for building it from source by `go get` , so we need to optimise history

Suggestions:
- Delete old branches (?)
- Make new branch
- Find commits with included binaries, squash them into one commit
- Open pull request to master
- Make **rebase** master to new branch

**Comment by ChronosX88** [comment]
We just need delete binary file (`git rm`). That's all.

**Comment by JackBekket** [comment]
> We just need delete binary files (`git rm`). That's all.

we need to delete files from commits, I mean overwrite commits somehow. 

But you can do it any way your prefer ^_^

**Comment by ChronosX88** [comment]
Cleaned by [BFG Repo-cleaner](https://rtyley.github.io/bfg-repo-cleaner).
